# Generated by Django 5.1.4 on 2025-04-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_hotels_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Property Finder',
                'verbose_name_plural': 'Property Finder',
            },
        ),
    ]
